### PR TITLE
added inversion flag

### PR DESCRIPTION
**Pull request by ZacharyTaylor**
@marco-tranzatto it seems like the transform between the cameras is inverted when it is read in (no idea why though). The depth still looks bad so maybe something else is going on...

Anyway as a test I added a flag "invert_T" you can set to flip things. Will investigate further when I get some more time.

### CODE REVIEW

**Comment by marco-tranzatto** [comment]
Hi @ZacharyTaylor 

I tested this branch today and these are the results:

**T_invert = false**
vi_tinvert_false

**T_invert = true**
vi_tinvert_true

It looks definitely better even though I still have some mismatches when projecting the URDF model of the robot in the camera stream in rviz. I will investigate this further.
Do you think we can merge this "T_invert" branch? If so, I'm happy to add some info in the readme file.

**Comment by ZacharyTaylor** [comment]
I am concerned this may still just be masking an underlying issue, but will merge as its useful to have anyway.

Also for aligning the URDF model how do you get the transform from Anymals body frame to the sensor?

**Comment by marco-tranzatto** [comment]
I estimated the transformation from robot's IMU to ViSensor's IMU with [kalibr Multi-IMU-and-IMU-intrinsic-calibration](https://github.com/ethz-asl/kalibr/wiki/Multi-IMU-and-IMU-intrinsic-calibration) and put it in the URDF model.

**Comment by marco-tranzatto** [comment]
@ZacharyTaylor by the way, given that this seems a temp fix. should I open a PR to update the readme file with this new param or would you rather keep it under the hood?

**Comment by ZacharyTaylor** [comment]
I already added a short line to the readme, I figure expose all the functionality

**Pull request merged**
